### PR TITLE
Add Google templates

### PR DESCRIPTION
**Pull request by frodenas**
This PR upgrades BOSH release to v257.9 and SHIELD release to v6.3.6 and adds Google templates. It also moves Shield templates from global to site templates because we cannot deploy the google-cpi-release and shield-release at the same deployment (when using bosh-init) due to a package conflict (golang).

### CODE REVIEW

**Comment by geofffranks** [comment]
Should we rename the shield golang package, or drop golang and use pre compiled binaries in its boshrelease to ease that?

**Comment by frodenas** [comment]
Whatever is easier. I personally don't like using specific names for packages (ie `shield-golang`), but shipping pre-compiled binaries will limit the ability to build shield from the latest source (ie to do some testing before shipping a new release).

**Comment by jhunt** [comment]
I vote for the pre-compiled binary approach.  If you want a different pre-compiled binary, just pre-compile it before you cut a dev release.

**Comment by frodenas** [comment]
@geofffranks @jhunt Should we use the pre-compiled binary approach then? If yes, I'll update the shield bosh release.

**Comment by jhunt** [comment]
I actually submitted a PR over the weekend to move to pre-compiled release binaries in Shield BOSH release: https://github.com/starkandwayne/shield/pull/219

**Comment by jhunt** [comment]
Latest SHIELD uses binaries and no longer has a `golang` package of its own, so I think we can move stuff back to global?

**Comment by geofffranks** [comment]
@frodenas let's go with the precompiled approach. also can you work through the merge conflicts?

**Comment by frodenas** [comment]
@geofffranks rebased against latest master, should be ok to merge now.

**Pull request merged**
